import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WalletConnect from "./services/providers/WalletConnect";
import { Toaster } from "@/app/components/ui/sonner"




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className="w-full bg-gray-950 min-h-screen">
          <WalletConnect>
             {children}
            </WalletConnect>  
           <Toaster />
        </div>
        </body>
    </html>
  );
}
